name: Python CI/CD

on:
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Linting and Testing
        run: |
          flake8 .
          python -m unittest discover -v

      - name: Code Coverage
        run: |
          pip install coverage
          coverage run -m unittest discover
          coverage report -m

      - name: Send Notifications on Success
        if: success()
        run: echo "Tests passed successfully. Merging pull request."

      - name: Send Notifications on Failure
        if: failure()
        run: echo "Tests failed. Check the build logs for details."

      - name: Auto Merge Pull Request
        if: success()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull origin ${{ github.event.pull_request.head.ref}}
          git merge --no-ff ${{ github.event.pull_request.head.sha}}
          git push origin ${{ github.event.pull_request.head.ref}}